services:
  acl.resource.transformator:
    class: AclBundle\Resource\Transformer\Transformator

  acl.resource.transformer.default:
    class: AclBundle\Resource\Transformer\DefaultTransformer
    tags:
      - { name: acl.resource.transformer, priority: -255 }

  acl.resource.transformer.doctrine:
    class: AclBundle\Resource\Transformer\DoctrineTransformer
    arguments: [@doctrine]
    tags:
      - { name: acl.resource.transformer, priority: -10 }
