services:
  # adds tags based on configuration
  acl.resource.provider.config:
    class: AclBundle\Resource\Provider\ConfigProvider
    arguments: [@kernel]

  acl.resource.provider.annotation:
    class: AclBundle\Resource\Provider\AnnotationProvider
    arguments: [@annotation_reader, @router]
