<?php

namespace AclBundle\Resource;

use Symfony\Component\HttpKernel\CacheWarmer\WarmableInterface;
use Symfony\Component\Config\ConfigCache;

class Builder implements WarmableInterface
{
    private $tree;
    private $providers = [];

    private $defaultAllowed = false;
    private $cacheDir;
    private $cachePrefix;
    private $debug;

    public function __construct(array $options)
    {
        list(
            $this->defaultAllowed,
            $this->cachePrefix,
            $this->debug
        ) = $options;
    }

    public function registerProvider(ProviderInterface $provider)
    {
        $this->providers[] = $provider;
    }

    /**
     * {@inheritdoc}
     */
    public function warmUp($cacheDir)
    {
        $this->cacheDir = $cacheDir;
        $this->getTree();
    }

    public function getTree()
    {
        if (null !== $this->tree) {
            return $this->tree;
        }

        $class = $this->cacheClass();
        $cache = new ConfigCache($this->cacheDir.'/'.$class.'.php', $this->debug);

        if (!$cache->isFresh()) {
            $content = $this->buildResourceTree($this->loadAll());
            $cache->write($content);
        }
        require_once $cache;
        return $this->tree = new $class();
    }

    protected function loadAll()
    {
        $resources = [];
        foreach ($this->providers as $provider) {
            $resources = array_merge($resources, $provider->getResources());
        }
        $this->validate($resources);
        return $resources;
    }

    protected function validate(array $resources)
    {
        foreach ($resources as $resource => $actions) {
            if (count($actions) === 0) {
                throw new \UnexpectedValueException("ACL resource \"{$resource}\" must have at least one action");
            }

            if (preg_match('/[^a-z0-9_\.]/', $resource)) {
                throw new \UnexpectedValueException("ACL resource \"{$resource}\" can have only lowercase ASCII characters, dots and underscores");
            }

            if (preg_match('/\.$/', $resource)) {
                throw new \UnexpectedValueException("ACL resource \"{$resource}\" cannot end with a dot");
            }

            if (preg_match('/\.^/', $resource)) {
                throw new \UnexpectedValueException("ACL resource \"{$resource}\" cannot start with a dot");
            }

            foreach ($actions as $action) {
                if (preg_match('/[^a-z_]/', $action)) {
                    throw new \UnexpectedValueException("ACL resource \"{$resource}\" action \"{$action}\" can have only lowercase ASCII characters and underscores");
                }
            }
        }
    }

    protected function cacheClass()
    {
        $parts = explode('\\', get_called_class());
        return $this->cachePrefix . end($parts);
    }

    /**
     * Takes all available application ACL resources and
     * builds an ACL tree cache class body
     *
     * @param array $resources - ['resource.string' => ['edit', 'view']]
     * @return string
     */
    protected function buildResourceTree(array $resources)
    {
        $store = [];
        foreach ($resources as $resource => $actions) {
            $next = &$store;
            $parts = explode('.', $resource);
            while ($part = array_shift($parts)) {
                if (!array_key_exists($part, $next)) {
                    $next[$part] = [];
                }
                $next = &$next[$part];
            }
            foreach ($actions as $action) {
                $next[$action] = $this->defaultAllowed;
            }
        }

        $resources = var_export($store, true);
        return <<<EOF
<?php

use AclBundle\Resource\Tree;

/**
 * This class has been auto-generated by the AclBundle.
 */
class {$this->cacheClass()} extends Tree
{
    protected \$resources = {$resources};
}
EOF;
    }
}
